### PR TITLE
Articles table pulled from main. Closes #38

### LINKED ISSUE #38: Create database table for Articles
# Dependencies

This issue should be completed *after* the issue "Articles - Create personal dokku dev deployment"

# Overview

This issue involves creating the database table and migration file for `Articles`.

For step-by-step instructions, please see these portions of the
lab writeup:

* <https://ucsb-cs156.github.io/w24/lab/team02.html#the-two-database-tables-in-the-starting-code>
* <https://ucsb-cs156.github.io/w24/lab/team02.html#your-task-add-crud-for-additional-database-tables>
* <https://ucsb-cs156.github.io/w24/lab/team02.html#adding-a-database-table>

# Acceptance Criteria:

- [x] There is an `@Entity` class called Articles.java
- [x] There is a `@Repository` class called ArticlesRepository.java
- [x] There is a database migration file called Articles.json
- [ ] When you start up the repo on localhost, you can see the table
      using the H2 console (see the file [`docs/h2-database.md`](/ucsb-cs156-w24/STARTER-team02/blob/main/docs/h2-database.md) for 
      instructions.)
- [ ] When you deploy the app to Dokku, you can see the table
      using the `dokku postgres:connect team02-db` command
      (use `\dt` to list the tables) (See <https://ucsb-cs156.github.io/topics/dokku/postgres_database.html#postgres-command-line> for more info.)

# What to do next

When you've met all of the acceptance criteria:

**Make a PR**: Do a PR for this branch, being sure to enter a [reasonable title](https://ucsb-cs156.github.io/topics/pull_requests.html#pr-titles)
and [description](https://ucsb-cs156.github.io/topics/pull_requests.html#pr-descriptions).

In the description, include the text "Closes #n" where `n` is the number of
this issue.

Then ask for a team member to review your PR.

Finally: drag this issue from "In Progress" to "In Review".

**Review Others' PRs**: Next, see if there are any PRs that need to be code reviewed and merged.  Unless you are the
first person on your team to complete a PR, there likely is at least one.
See: 
* [General Code Review Advice](https://ucsb-cs156.github.io/topics/code_reviews/)
* [Performin Code Reviews on Github](https://ucsb-cs156.github.io/topics/code_reviews/code_reviews_github.html)

**Start your next issue **: Then, find the issue for 
"Create `ArticlesController..." on the Kanban board in the ToDo column.

* Assign it to yourself
* Drag into "In Progress"
* Create a new branch, starting from the branch for the issue you just finished.
* Start on the new issue.

### PR DESCRIPTION
**Pull request by anirudhiyer1**
I fixed the order of the database in the json file and renamed everything to articles 
Closes #38

### CODE REVIEW

**Review by ColeFoster08 — COMMENTED** [review]
The database should be titled Articles, and the entries in the table are entered in reverse order. Also can you add a description to the pull request and link it with it's corresponding issue from the Kanban board (In this case it is #38).

**Comment by Cory-Zhao** [comment]
Local host does not work for me. 

There seems to be a problem with your deployment. Likely an issue when you were configuring the app and oauth. 
Screenshot 2024-02-13 at 2 02 04 PM
For all other apps, I see an https link along with the http link, which I didn't see here. 

When I opened the link, I could not log in with my email either.
Screenshot 2024-02-13 at 2 04 24 PM


I'm not sure if this is from my end, but this is the first time I had this problem.

**Comment by ColeFoster08** [comment]
> Local host does not work for me.
> 
> There seems to be a problem with your deployment. Likely an issue when you were configuring the app and oauth. Screenshot 2024-02-13 at 2 02 04 PM For all other apps, I see an https link along with the http link, which I didn't see here.
> 
> When I opened the link, I could not log in with my email either. Screenshot 2024-02-13 at 2 04 24 PM
> 
> I'm not sure if this is from my end, but this is the first time I had this problem.

For this issue, the solution is likely one of three things. First, confirm that the google_client_id and google_client_secret are used correctly in the dokku config:show for your development app. Another thing to check would be to ensure that the authorized redirect URI's are configured correctly on https://console.cloud.google.com/ to look something like this:
Screenshot 2024-02-13 at 2 14 31 PM
The last thing to check would be that you correctly followed the steps to configure HTTPS for the app (https://ucsb-cs156.github.io/topics/dokku/enabling_https.html)

**Comment by anirudhiyer1** [comment]
Can you check again? I enabled https and added your guys' emails and it works for me on local and https. 

https://team02-anirudhiyer1-dev.dokku-08.cs.ucsb.edu

**Comment by ColeFoster08** [comment]
> Can you check again? I enabled https and added your guys' emails and it works for me on local and https.
> 
> https://team02-anirudhiyer1-dev.dokku-08.cs.ucsb.edu

It worked for me when I used that link

**Comment by anirudhiyer1** [comment]
> > Can you check again? I enabled https and added your guys' emails and it works for me on local and https.
> > https://team02-anirudhiyer1-dev.dokku-08.cs.ucsb.edu
> 
> It worked for me when I used that link

Does it work on your localhost as well

**Review by ColeFoster08 — APPROVED** [review]
LGTM

**Pull request merged**
